### ISSUE TITLE
Bug - Sparkline is drawn twice on render

### ISSUE THREAD

**Issue by dalerasrorov-eb** [eventbrite/britecharts-react#129]
For some reason, the Sparkline chart is being re-rendered on refresh instead of doing it just once. This happens only for animated chart. Look at GIF screenshot

## Expected Behavior
Should render animated chart once without re-drawing.

## Current Behavior
Draws Sparkline with animation twice

## Possible Solution
Something has to do with update and animation. React chart component is probably changing the state when it doesn't need to.

## Steps to Reproduce (for bugs)

1. Go to Sparkline chart section
2. Refresh the page

## Screenshots (if appropriate):
![britecharts_sparkline_bug](https://user-images.githubusercontent.com/31934144/37746927-cacc68e6-2d39-11e8-9b64-c8fc0badd300.gif)

## Your Environment

* Version used:
* Browser Name and version: Chrome
* Operating System and version:
* Link to your project or codepen:

**Comment by miglesiasEB** [comment]
I haven't been able to reproduce this one, do you still see it @DalerAsrorov ?

**Comment by davegomez** [comment]
@Golodhros I have been looking into this issue and what is really happening is that (at least in the docs) the Sparkline chart is re drawn because the responsive behavior is applied to it and it happens with every other responsive chart with the loading state active.

Every time the size of the chart changes the animation starts again.

One possible "solution" considering this as an issue would be to run the responsive re drawn before the animation, but so far I have no idea how we could accomplish that.

**Comment by Golodhros** [comment]
Hi @davegomez,

Oh, actually this got fixed! It was doing it twice, now works great!

I think it had to do with your fix in the responsive container.

Thanks!
