### ISSUE TITLE
Parse error when when generating chart boilerplate via plop

### ISSUE THREAD

**Issue by dburandt** [eventbrite/britecharts-react#151]
Hi there! I wanted to take a stab at creating a Scatter Plot, but I'm getting an error when I try to use plop to generate the boilerplate code.

## Expected Behavior
Plop should generate 7 boilerplate files for a Scatter Plot.

## Current Behavior
I get the following error:

```
? Component name (with PascalCase capitalization, eg StackedArea) ScatterPlot
[SUCCESS] add /src/charts/scatterPlot/scatterPlotChart.test.js
[SUCCESS] add /src/charts/scatterPlot/scatterPlotChart.js
[SUCCESS] add /src/charts/scatterPlot/scatterPlotChart.fixtures.js
[SUCCESS] add /src/charts/scatterPlot/ScatterPlot.js
[FAILED] add Parse error on line 26:
...lCase componentName }    }Data.firstDat
-----------------------^
Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'EQUALS', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', 'SEP', got 'INVALID'
[FAILED] add src/charts/{{camelCase componentName}}/Readme.md Aborted due to previous action failure
[FAILED] add src/charts/{{camelCase componentName}}/Checklist.md Aborted due to previous action failure
```

## Possible Solution
Looks like maybe a missing bracket in Component.test.js. I couldn't find the fix after a few minutes but i may give it another go later and submit a PR if I fix it.

## Your Environment

* Version used: Node v11.2.0
* Operating System and version: macOS 10.14.2

**Comment by DalerAsrorov** [comment]
I just created a PR for the fix: https://github.com/eventbrite/britecharts-react/pull/152. Turns out the problem was with the `Component.test.js` template file since it's been changed. You can wait until this PR is merged or remove this section of code https://github.com/eventbrite/britecharts-react/blob/master/plopfile.js#L31-L35 and create a custom file with tests in this path `src/charts/scatterPlot/ScatterPlot.test.js` instead.
