### ISSUE TITLE
Chart does not render with Tooltip when data is progressively added

### ISSUE THREAD

**Issue by mitom** [eventbrite/britecharts-react#155]
## Expected Behavior
When a chart is set to render with a tooltip and data is progressively added, the chart should render and update continuously. This works _without_ a tooltip: https://codepen.io/anon/pen/zXPVba

## Current Behavior
The chart renders, but the data line is not shown: https://codepen.io/anon/pen/EJbJGq

## Possible Solution
Not sure, may be something I did wrong?

## Steps to Reproduce (for bugs)
https://codepen.io/anon/pen/EJbJGq

## Context
Trying to create a chart that displays live monitoring data, new datapoints are expected to be added at most every second. 

## Your Environment
Chrome Version 73.0.3683.103 (Official Build) (64-bit)
OSX mojave 10.14.4

**Comment by davegomez** [comment]
@mitom did you check the workaround proposed in the issue #116?

**Comment by mitom** [comment]
@davegomez I gave it a go just now. I'm not sure if I'm not applying that correctly, but it seems to behave the exact same for me: https://codepen.io/anon/pen/EJbJGq

**Comment by davegomez** [comment]
@mitom in your example you are using the time interval to render the component, so this will render just once and will be remove the next time the setInterval hits. You have to use the setInterval to update the props, not ro render the component.

I can't give it a try right now because I'm busy try to do what I told you and let me know if it helps.

I can give it a try later.

**Comment by mitom** [comment]
Thank you for the answer @davegomez, I was able to figure it out. For anyone who gets stuck on this, here is the working example: https://codepen.io/anon/pen/QPaNBR
