### ISSUE TITLE
Update to react 16

### ISSUE THREAD

**Issue by rubenmoya** [eventbrite/britecharts-react#78]
Are we going to update the project to React 16?

**Comment by jchen-eb** [comment]
That's a great idea. One issue though is that we're using britecharts-react in our company's app that's on React 15, I'm not sure if it will still work if there are two different versions of React. But our company's app will eventually be on React 16 so we will definitely make the upgrade at some point. Either way it's worth investigating to see if we can upgrade britecharts-react to React 16 first, I'll spend some time looking into it today.

**Comment by jchen-eb** [comment]
So we *could* upgrade the project to React 16, but we would need to maintain compatibility with React 15 so that this module could be used within a React 15 app without needing to bundle an additional version of React 16. That would probably mean either:

1) Only use the parts of the React API that are compatible with both React 15 and 16. That way somebody could, in theory, use this module in both React 15 and 16 apps. I haven't looked into how feasible this is.

2) Include both a React 16-compatible and a React 15-compatible distribution file, similar to how Enzyme does it: http://airbnb.io/enzyme/ I feel like this will end up being difficult to maintain, we don't really have the capacity to do this and would have to rely more on open source contributions to make it work. But it could be a good way to go.

**Comment by Golodhros** [comment]
Let's wait then. We can leave this open as a 'proposal' and move it depending on the push of the community for it.

**Comment by benmvp** [comment]
The next big project for Frontend Platform team is React 16 so hopefully it won't be too long from now!

**Comment by sdalezman** [comment]
We're using britecharts with react-16 and haven't had any problems yet (outside of some issues with react-test-renderer that we've worked around).

That being said, would love to see official support!

**Comment by Golodhros** [comment]
Uohhh! Thanks for the heads up @sdalezman!

Let's see if we manage to move it soon!

**Comment by davegomez** [comment]
@Golodhros and @jchen-eb I would like to work on this and see if I can add support and as many new features while keeping the compatibility with React 15. Will be fun 😁

**Comment by Golodhros** [comment]
That would be awesome @davegomez!!

I am pushing for having our release issue fixed so we can start moving forward, hope it is done by next week!

Re: Flow, it seems that somebody is looking into adding Typescript to Britecharts and we want to have it open to different platforms (using this code to fuel the Angular and Vue wrappers). Not sure if Flow fits well into this strategy.

**Comment by davegomez** [comment]
@Golodhros you should close this issue too.

**Comment by miglesiasEB** [comment]
Thanks @davegomez for this!!
